<a href="https://colab.research.google.com/github/adams-gc/QNN/blob/basic-of-quantum-physics/Qiskit_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Qiskit **implementation**
- Need Before Running the Code
    - pip install qiskit
    - pip install matplotlib


In [1]:
!pip install qiskit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 82.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 88.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.4/54.4 kB 4.7 MB/s eta 0:00:00


In [2]:
!pip install qiskit
!pip install matplotlib

In [3]:
from qiskit import __version__
print(__version__)

2.3.0


#Python Basics: Vectors and Matrices

- A qubit state is represented as a 2×1 column vector. In Qiskit we often use NumPy to build and manipulate these.

In [4]:
'''defines two column vectors, ket0 and ket1, corresponding to the qubit state vectors
∣0⟩ and ∣1⟩, and then prints their average.'''

import numpy as np

ket0 = np.array([[1],[0]])  # |0⟩
ket1 = np.array([[0],[1]])  # |1⟩
print(np.average(ket0),np.average(ket1))
print("##############################")

print(ket0 / 2 + ket1 / 2 )


0.5 0.5
##############################
[[0.5]
 [0.5]]


#this shows a superposition (equal parts |0⟩ and |1⟩) using matrix mathhis .



- #multiply matrices and vectors with np.matmul, which is how quantum gates act on states

In [10]:
# M0= np.array([[1,1], [0,0] ])# thisis constant 0 matrix
# # M1= np.array ([[0,0] ,[1,1] ])# this constangt one
# M2= np.array ([[1,0], [0,1]]) # this identity matrix
# M=M0/3 + M2/2 # + M0/2
# print(M)

M1 = np.array([[1, 1], [0, 0]])
M2 = np.array([[1, 0], [0, 1]])
M = M1 / 2 + M2 / 2
print(M)

# print(np.matmul(M0,ket1)) #these operations as applying gates by matrix multiplication.these operations as applying gates by matrix multiplication.

[[1.  0.5]
 [0.  0.5]]


In [14]:
M0= np.array([[1,1], [0,0] ])# thisis constant 0 matrix
M1= np.array ([[0,0] ,[1,1] ])# this constangt one
M2= np.array ([[1,0], [0,1]]) # this identity matrix
M=M0/2 + M2/2 # + M0/2
N=M0/3 + M1/3  + M2/3
print(M)
print("############")
print(N)

[[1.  0.5]
 [0.  0.5]]
############
[[0.66666667 0.33333333]
 [0.33333333 0.66666667]]


In [ ]:
#

print(np.matmul(M0,ket1)) #these operations as applying gates by matrix multiplication.these operations as applying gates by matrix multiplication.